### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ZxcSosock** [P0L3NARUBA/friday-13th-game-hacks#1]
как открыть меню трейнера

**Comment by yungDoom** [comment]
Insert

**Comment by ZxcSosock** [comment]
пасиб

**Comment by yungDoom** [comment]
👍🏿

**Comment by ZxcSosock** [comment]
Uploading Friday the 13th_ The Game  - B12506 2024-06-25 21-42-08.mp4…

**Comment by ZxcSosock** [comment]
https://wdho.ru/bB4n не открывает чото

**Comment by yungDoom** [comment]
did you unpacked the game?

**Comment by ZxcSosock** [comment]
yes

**Comment by yungDoom** [comment]
do you think that you put the folders to the correct location?

**Comment by ZxcSosock** [comment]
yes

**Comment by ZxcSosock** [comment]
I can shoot it on video, but I need to download obs studio

**Comment by yungDoom** [comment]
It should be Insert key, can you try another keyboard that has insert key? you can bind the custom key later on the mod menu.

**Comment by ZxcSosock** [comment]
ins is an insert

**Comment by yungDoom** [comment]
yeah but its odd because it needs to work if you set the mod menu correctly.

**Comment by ZxcSosock** [comment]
I moved summercamp in Friday the 13th the game and that's it

**Comment by yungDoom** [comment]
do you have discord?

**Comment by ZxcSosock** [comment]
yes

**Comment by ZxcSosock** [comment]
zxcsosock

**Comment by ZxcSosock** [comment]
but i russian

**Comment by yungDoom** [comment]
The issue has been solved!
